# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lamoda.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'lamoda.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clamoda.proto\x12\x06lamoda\"\x1f\n\x0f\x43\x61tegoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"#\n\x10\x43\x61tegoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32]\n\rLamodaService\x12L\n\x17\x43reateCategoryDirectory\x12\x17.lamoda.CategoryRequest\x1a\x18.lamoda.CategoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lamoda_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYREQUEST']._serialized_start=24
  _globals['_CATEGORYREQUEST']._serialized_end=55
  _globals['_CATEGORYRESPONSE']._serialized_start=57
  _globals['_CATEGORYRESPONSE']._serialized_end=92
  _globals['_LAMODASERVICE']._serialized_start=94
  _globals['_LAMODASERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
