# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fileexchange.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fileexchange.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ileexchange.proto\x12\x0c\x46ileExchange\"/\n\x08\x46ileData\x12\x10\n\x08\x46ileName\x18\x01 \x01(\t\x12\x11\n\tChunkData\x18\x02 \x01(\x0c\"M\n\x0cUploadStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\x12,\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x1e.FileExchange.UploadStatusCode*&\n\x10UploadStatusCode\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32N\n\x0c\x46ileExchange\x12>\n\x06Upload\x12\x16.FileExchange.FileData\x1a\x1a.FileExchange.UploadStatus(\x01\x42\x0f\xaa\x02\x0c\x46ileExchangeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fileexchange_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\014FileExchange'
  _globals['_UPLOADSTATUSCODE']._serialized_start=164
  _globals['_UPLOADSTATUSCODE']._serialized_end=202
  _globals['_FILEDATA']._serialized_start=36
  _globals['_FILEDATA']._serialized_end=83
  _globals['_UPLOADSTATUS']._serialized_start=85
  _globals['_UPLOADSTATUS']._serialized_end=162
  _globals['_FILEEXCHANGE']._serialized_start=204
  _globals['_FILEEXCHANGE']._serialized_end=282
# @@protoc_insertion_point(module_scope)
