# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processingdatabase.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'processingdatabase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fileexchange_pb2 as fileexchange__pb2

from fileexchange_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18processingdatabase.proto\x12\x12ProcessingDatabase\x1a\x12\x66ileexchange.proto\":\n\x10\x45mbeddingRequest\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x01(\t\"m\n\rInsertRequest\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .ProcessingDatabase.RecordStatus\x12*\n\x06record\x18\x02 \x01(\x0b\x32\x1a.ProcessingDatabase.Record\"A\n\x0cInsertResult\x12\x31\n\x06result\x18\x01 \x01(\x0b\x32!.ProcessingDatabase.CommandResult\"F\n\x12GetByStatusRequest\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .ProcessingDatabase.RecordStatus\"r\n\x11GetByStatusResult\x12*\n\x06record\x18\x01 \x01(\x0b\x32\x1a.ProcessingDatabase.Record\x12\x31\n\x06result\x18\x02 \x01(\x0b\x32!.ProcessingDatabase.CommandResult\"?\n\x11UpdateByIDRequest\x12*\n\x06record\x18\x01 \x01(\x0b\x32\x1a.ProcessingDatabase.Record\"E\n\x10UpdateByIDResult\x12\x31\n\x06result\x18\x01 \x01(\x0b\x32!.ProcessingDatabase.CommandResult\"\x16\n\x06Record\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"8\n\rCommandResult\x12\x11\n\terrorCode\x18\x01 \x01(\x05\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t*R\n\x0cRecordStatus\x12\x07\n\x03NEW\x10\x00\x12\x10\n\x0cPREPROCESSED\x10\x01\x12\x0e\n\nPROCEESSED\x10\x02\x12\x0c\n\x08\x46INISHED\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x32\xdf\x02\n\x12ProcessingDatabase\x12M\n\x06Insert\x12!.ProcessingDatabase.InsertRequest\x1a .ProcessingDatabase.InsertResult\x12\x41\n\tImportCSV\x12\x16.FileExchange.FileData\x1a\x1a.FileExchange.UploadStatus(\x01\x12\\\n\x0bGetByStatus\x12&.ProcessingDatabase.GetByStatusRequest\x1a%.ProcessingDatabase.GetByStatusResult\x12Y\n\nUpdateByID\x12%.ProcessingDatabase.UpdateByIDRequest\x1a$.ProcessingDatabase.UpdateByIDResult2t\n\x15ImageEmbeddingService\x12[\n\x0cProcessImage\x12$.ProcessingDatabase.EmbeddingRequest\x1a%.ProcessingDatabase.EmbeddingResponseB\x15\xaa\x02\x12ProcessingDatabaseP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processingdatabase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\022ProcessingDatabase'
  _globals['_RECORDSTATUS']._serialized_start=752
  _globals['_RECORDSTATUS']._serialized_end=834
  _globals['_EMBEDDINGREQUEST']._serialized_start=68
  _globals['_EMBEDDINGREQUEST']._serialized_end=126
  _globals['_EMBEDDINGRESPONSE']._serialized_start=128
  _globals['_EMBEDDINGRESPONSE']._serialized_end=166
  _globals['_INSERTREQUEST']._serialized_start=168
  _globals['_INSERTREQUEST']._serialized_end=277
  _globals['_INSERTRESULT']._serialized_start=279
  _globals['_INSERTRESULT']._serialized_end=344
  _globals['_GETBYSTATUSREQUEST']._serialized_start=346
  _globals['_GETBYSTATUSREQUEST']._serialized_end=416
  _globals['_GETBYSTATUSRESULT']._serialized_start=418
  _globals['_GETBYSTATUSRESULT']._serialized_end=532
  _globals['_UPDATEBYIDREQUEST']._serialized_start=534
  _globals['_UPDATEBYIDREQUEST']._serialized_end=597
  _globals['_UPDATEBYIDRESULT']._serialized_start=599
  _globals['_UPDATEBYIDRESULT']._serialized_end=668
  _globals['_RECORD']._serialized_start=670
  _globals['_RECORD']._serialized_end=692
  _globals['_COMMANDRESULT']._serialized_start=694
  _globals['_COMMANDRESULT']._serialized_end=750
  _globals['_PROCESSINGDATABASE']._serialized_start=837
  _globals['_PROCESSINGDATABASE']._serialized_end=1188
  _globals['_IMAGEEMBEDDINGSERVICE']._serialized_start=1190
  _globals['_IMAGEEMBEDDINGSERVICE']._serialized_end=1306
# @@protoc_insertion_point(module_scope)
