# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scraper_pb2 as scraper__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scraper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScraperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTagsByCategory = channel.unary_unary(
                '/scraper.ScraperService/SendTagsByCategory',
                request_serializer=scraper__pb2.TagsByCategoryRequest.SerializeToString,
                response_deserializer=scraper__pb2.TagsByCategoryResponse.FromString,
                _registered_method=True)
        self.SendSubcategoriesByCategory = channel.unary_unary(
                '/scraper.ScraperService/SendSubcategoriesByCategory',
                request_serializer=scraper__pb2.SubcategoriesByCategoryRequest.SerializeToString,
                response_deserializer=scraper__pb2.SubcategoriesByCategoryResponse.FromString,
                _registered_method=True)
        self.SendParsedCSVRow = channel.unary_unary(
                '/scraper.ScraperService/SendParsedCSVRow',
                request_serializer=scraper__pb2.ParsedCSVRowRequest.SerializeToString,
                response_deserializer=scraper__pb2.ParsedCSVRowResponse.FromString,
                _registered_method=True)


class ScraperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTagsByCategory(self, request, context):
        """Метод для отправки словаря с категориями и тегами
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendSubcategoriesByCategory(self, request, context):
        """Метод для отправки словаря с подкатегориями
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendParsedCSVRow(self, request, context):
        """Метод для отправки строки из CSV-файла
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScraperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTagsByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTagsByCategory,
                    request_deserializer=scraper__pb2.TagsByCategoryRequest.FromString,
                    response_serializer=scraper__pb2.TagsByCategoryResponse.SerializeToString,
            ),
            'SendSubcategoriesByCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSubcategoriesByCategory,
                    request_deserializer=scraper__pb2.SubcategoriesByCategoryRequest.FromString,
                    response_serializer=scraper__pb2.SubcategoriesByCategoryResponse.SerializeToString,
            ),
            'SendParsedCSVRow': grpc.unary_unary_rpc_method_handler(
                    servicer.SendParsedCSVRow,
                    request_deserializer=scraper__pb2.ParsedCSVRowRequest.FromString,
                    response_serializer=scraper__pb2.ParsedCSVRowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraper.ScraperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scraper.ScraperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScraperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTagsByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/SendTagsByCategory',
            scraper__pb2.TagsByCategoryRequest.SerializeToString,
            scraper__pb2.TagsByCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendSubcategoriesByCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/SendSubcategoriesByCategory',
            scraper__pb2.SubcategoriesByCategoryRequest.SerializeToString,
            scraper__pb2.SubcategoriesByCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendParsedCSVRow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraper.ScraperService/SendParsedCSVRow',
            scraper__pb2.ParsedCSVRowRequest.SerializeToString,
            scraper__pb2.ParsedCSVRowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
