# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_embedding.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'image_embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_embedding.proto\":\n\x10\x45mbeddingRequest\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x01(\t2N\n\x15ImageEmbeddingService\x12\x35\n\x0cProcessImage\x12\x11.EmbeddingRequest\x1a\x12.EmbeddingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGREQUEST']._serialized_start=25
  _globals['_EMBEDDINGREQUEST']._serialized_end=83
  _globals['_EMBEDDINGRESPONSE']._serialized_start=85
  _globals['_EMBEDDINGRESPONSE']._serialized_end=123
  _globals['_IMAGEEMBEDDINGSERVICE']._serialized_start=125
  _globals['_IMAGEEMBEDDINGSERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
